library(RGAP)
data("gap")
tsList<-amecoData2input(gap[["France"]],alpha=0.65)
model<-parRestr<-prior<-fit<-list()
D<-matrix(c(2,2,2,1,1,1),2,3,byrow=TRUE)
L<-matrix(c(0,0,0,1,1,1),2,3,byrow=TRUE)
exoType<-initializeExo(varNames=c("ws","prod","tot"),D=D,L=L)
model$nawru<-NAWRUmodel(tsl=tsList,trend="RW2",cycle="AR2",type="TKP",cycleLag=0,exoType=exoType)
model$tfp<-TFPmodel(tsl=tsList,trend="DT",cycle="RAR2",cycleLag=0,cubsErrorARMA=c(0,0))
parRestr$nawru<-initializeRestr(model=model$nawru,type="hp")
fits <- list()
fits$nawru <- fit(model=model$nawru,parRestr=parRestr$nawru)
parRestr$tfp<-initializeRestr(model=model$tfp,type="hp")
fits$tfp<-fit(model=model$tfp,parRestr=parRestr$tfp)
plot(fits$tfp)
fits$gap<-gapProd(tsl=tsList,NAWRUfit=fits$nawru,TFPfit=fits$tfp,lambda=100,alpha=0.65)
plot(fits$gap)
plot(fits$gap, contribution = TRUE)
